---

- name: Ensure app config updated
  template: >
    src=app.ini.j2
    dest=/home/git/gogs/custom/conf/app.ini
    mode=0755
    owner={{gogs_app_user}}
    group={{gogs_app_group}}
  notify: restart gogs

- name: Ensure init.d script is installed
  template: >
    src=etc/init.d/gogs.j2
    dest=/etc/init.d/gogs
    mode=0755
    owner=root
    group=root
  notify:
    - restart gogs
    - register gogs init

- name: Make sure app is running
  service: name=gogs state=running

- name: Make sure logrotate config installed
  template: >
    src=etc/logrotate.d/gogs.j2
    dest=/etc/logrotate.d/gogs
    mode=0755
    owner=root
    group=root

- name: Make sure app is running
  service: name=gogs state=running
