---

- name: Ensure app config updated
  template: >
    src=app.ini.j2
    dest=/home/git/gogs/custom/conf/app.ini
    mode=0755
    owner={{gogs_app_user}}
    group={{gogs_app_group}}
  notify: restart gogs

- name: Ensure init.d script is installed
  template: >
    src=etc/init.d/gogs.j2
    dest=/etc/init.d/gogs
    mode=0755
    owner=root
    group=root
  notify:
    - restart gogs
    - register gogs init

- name: Make sure app is running
  service: name=gogs state=running

- name: Make sure logrotate config installed
  template: >
    src=etc/logrotate.d/gogs.j2
    dest=/etc/logrotate.d/gogs
    mode=0755
    owner=root
    group=root

- name: Make sure nginx config installed
  template: >
    src=etc/nginx/sites-available/gogs.conf.j2
    dest=/etc/nginx/sites-available/gogs.conf
    mode=0755
    owner=root
    group=root
  notify: restart nginx

- name: Make sure nginx config enabled
  file: >
    src=/etc/nginx/sites-available/gogs.conf
    dest=/etc/nginx/sites-enabled/gogs.conf
    owner=root
    group=root
    state=link
  notify: restart nginx

- name: Make sure default nginx config is removed
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: Make sure app is running
  service: name=gogs state=running
